package com.unicom.eos.codebuysync.mapper;

import com.unicom.eos.codebuysync.entity.Order;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.jdbc.SQL;
import org.apache.ibatis.type.JdbcType;

import com.unicom.eos.codebuysync.entity.OrderDispatch;
import com.unicom.eos.codebuysync.entity.OrderIndex;
import com.unicom.eos.codebuysync.mybatis.DataSecurityHandler;

@Mapper
public interface OrderDispatchMapper {
    
    @Select({"<script>",
            "SELECT order_id,dn,log_dn,post_addr,province_code,city_code from tf_b_order_index " +
                    "where order_id = #{orderId}" +
                    "<if test=\" provinceCode != null \">" +
                    " and province_code = #{provinceCode}" +
                    "</if>"
            ,"</script>"})
    @Results({
        @Result(column = "order_id", property = "orderId"),
        @Result(column = "log_dn", property = "logDn"),
        @Result(column = "post_addr", property = "postAddr", typeHandler = DataSecurityHandler.class),
        @Result(column = "province_code", property = "provinceCode"),
        @Result(column = "city_code", property = "cityCode"),
    })
    OrderIndex findOrderIndexByOrderId(@Param("orderId") Long orderId,@Param("provinceCode") String provinceCode);

    @Select("SELECT wideband_order_id,0 dn,0 log_dn,install_address,province_code,city_code from tf_b_order_wideband_info " +
                    "where wideband_order_id = #{orderId}")
    @Results({
            @Result(column = "wideband_order_id", property = "orderId"),
            @Result(column = "log_dn", property = "logDn"),
            @Result(column = "install_address", property = "postAddr"),
            @Result(column = "province_code", property = "provinceCode"),
            @Result(column = "city_code", property = "cityCode"),
    })
    OrderIndex findWidebandInfo(@Param("orderId") Long orderId);

    /**
     * 意向单修改订单状态
     * mashanggou 码上购标记 0物流 1上门 2自提 3码上购智能派单
     * deliver_type_code 01 快递 02 不需要配送 03 自提（TF_B_ORDER_SELFFETCH_RELE.SELF_TYPE查看是电商自提还是营业厅自提） 04 上来联通自提 05 自行配送 06 联通营业厅自提 07 上门激活
     * @param order
     * @return
     */
    @Update("update tf_b_order set order_state = #{orderState},mashanggou = 1, deliver_type_code = '07'" +
            " where dn = #{dn} and order_id = #{orderId}")
    int updateOrderState(Order order);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_order_dispatch
     *
     * @mbg.generated Wed Jun 26 09:42:08 CST 2019
     */
    @Delete({
        "delete from tf_b_order_dispatch",
        "where order_id = #{orderId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_order_dispatch
     *
     * @mbg.generated Wed Jun 26 09:42:08 CST 2019
     */
    @Insert({
        "insert into tf_b_order_dispatch (order_id, order_no, ",
        "business_type, order_delivery_intention, ",
        "order_creat_time, goods_name, ",
        "province_code_post, city_code_post, ",
        "district_code_post, post_addr, ",
        "dispatch_cmd_cate, dispatch_state, ",
        "dispatch_obj_type, dispatch_obj_subject, ",
        "dispatch_obj_tel, dispatch_obj_time, ",
        "manual_reason_cate, manual_reason_desc, ",
        "dispatch_recall_reason, dispatch_tag, ",
        "auto_dispatch_grid, auto_dispatch_refer, ",
        "auto_trace, map_point, ",
        "timeout_tag, order_assign_subject, ",
        "change_reason, dispatch_manager_tag, ",
        "update_staff, update_time, ",
        "remark, age_tag, change_type, ",
        "caller_type, broadband_order_id, ",
        "cross_city_tag, rsync_tag, ",
        "lock_tag, sys_channel, ",
        "bus_channel, product_id, ",
        "lock_reason, pool_tag, ",
        "com_code, post_phone, ",
        "broadband_cust_name, broadband_pspt_type_code, ",
        "broadband_pspt_no, appoint_date, ",
        "appoint_date_segment, second_pool_limit_tag, ",
        "post_addr_detail, user_appoint_end_time, ",
        "user_appoint_start_time, order_province_code, ",
        "order_city_code, enter_msgo_time, ",
        "callout_times, contact_time, ",
        "lock_expires_time, dn, ",
        "log_dn, age, sync_tag, ",
        "link_install_res_tag, link_install_addr, ",
        "province_name, city_name, ",
        "district_name)",
        "values (#{orderId,jdbcType=BIGINT}, #{orderNo,jdbcType=VARCHAR}, ",
        "#{businessType,jdbcType=VARCHAR}, #{orderDeliveryIntention,jdbcType=VARCHAR}, ",
        "#{orderCreatTime,jdbcType=TIMESTAMP}, #{goodsName,jdbcType=VARCHAR}, ",
        "#{provinceCodePost,jdbcType=VARCHAR}, #{cityCodePost,jdbcType=VARCHAR}, ",
        "#{districtCodePost,jdbcType=VARCHAR}, #{postAddr,jdbcType=VARCHAR}, ",
        "#{dispatchCmdCate,jdbcType=TINYINT}, #{dispatchState,jdbcType=TINYINT}, ",
        "#{dispatchObjType,jdbcType=TINYINT}, #{dispatchObjSubject,jdbcType=VARCHAR}, ",
        "#{dispatchObjTel,jdbcType=VARCHAR}, #{dispatchObjTime,jdbcType=TIMESTAMP}, ",
        "#{manualReasonCate,jdbcType=TINYINT}, #{manualReasonDesc,jdbcType=VARCHAR}, ",
        "#{dispatchRecallReason,jdbcType=VARCHAR}, #{dispatchTag,jdbcType=TINYINT}, ",
        "#{autoDispatchGrid,jdbcType=VARCHAR}, #{autoDispatchRefer,jdbcType=TINYINT}, ",
        "#{autoTrace,jdbcType=VARCHAR}, #{mapPoint,jdbcType=VARCHAR}, ",
        "#{timeoutTag,jdbcType=TINYINT}, #{orderAssignSubject,jdbcType=VARCHAR}, ",
        "#{changeReason,jdbcType=VARCHAR}, #{dispatchManagerTag,jdbcType=CHAR}, ",
        "#{updateStaff,jdbcType=VARCHAR}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{remark,jdbcType=VARCHAR}, #{ageTag,jdbcType=CHAR}, #{changeType,jdbcType=VARCHAR}, ",
        "#{callerType,jdbcType=VARCHAR}, #{broadbandOrderId,jdbcType=BIGINT}, ",
        "#{crossCityTag,jdbcType=TINYINT}, #{rsyncTag,jdbcType=TINYINT}, ",
        "#{lockTag,jdbcType=TINYINT}, #{sysChannel,jdbcType=VARCHAR}, ",
        "#{busChannel,jdbcType=VARCHAR}, #{productId,jdbcType=VARCHAR}, ",
        "#{lockReason,jdbcType=VARCHAR}, #{poolTag,jdbcType=TINYINT}, ",
        "#{comCode,jdbcType=CHAR}, #{postPhone,jdbcType=VARCHAR}, ",
        "#{broadbandCustName,jdbcType=VARCHAR}, #{broadbandPsptTypeCode,jdbcType=VARCHAR}, ",
        "#{broadbandPsptNo,jdbcType=VARCHAR}, #{appointDate,jdbcType=TIMESTAMP}, ",
        "#{appointDateSegment,jdbcType=TINYINT}, #{secondPoolLimitTag,jdbcType=TINYINT}, ",
        "#{postAddrDetail,jdbcType=VARCHAR}, #{userAppointEndTime,jdbcType=TIMESTAMP}, ",
        "#{userAppointStartTime,jdbcType=TIMESTAMP}, #{orderProvinceCode,jdbcType=VARCHAR}, ",
        "#{orderCityCode,jdbcType=VARCHAR}, #{enterMsgoTime,jdbcType=TIMESTAMP}, ",
        "#{calloutTimes,jdbcType=VARCHAR}, #{contactTime,jdbcType=TIMESTAMP}, ",
        "#{lockExpiresTime,jdbcType=TIMESTAMP}, #{dn,jdbcType=INTEGER}, ",
        "#{logDn,jdbcType=INTEGER}, #{age,jdbcType=INTEGER}, #{syncTag,jdbcType=TINYINT}, ",
        "#{linkInstallResTag,jdbcType=TINYINT}, #{linkInstallAddr,jdbcType=VARCHAR}, ",
        "#{provinceName,jdbcType=VARCHAR}, #{cityName,jdbcType=VARCHAR}, ",
        "#{districtName,jdbcType=VARCHAR})"
    })
    int insert(OrderDispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_order_dispatch
     *
     * @mbg.generated Wed Jun 26 09:42:08 CST 2019
     */
    @InsertProvider(type=OrderIDispatcSqlProvider.class, method="insertSelective")
    int insertSelective(OrderDispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_order_dispatch
     *
     * @mbg.generated Wed Jun 26 09:42:08 CST 2019
     */
    @Select({
        "select",
        "order_id, order_no, business_type, order_delivery_intention, order_creat_time, ",
        "goods_name, province_code_post, city_code_post, district_code_post, post_addr, ",
        "dispatch_cmd_cate, dispatch_state, dispatch_obj_type, dispatch_obj_subject, ",
        "dispatch_obj_tel, dispatch_obj_time, manual_reason_cate, manual_reason_desc, ",
        "dispatch_recall_reason, dispatch_tag, auto_dispatch_grid, auto_dispatch_refer, ",
        "auto_trace, map_point, timeout_tag, order_assign_subject, change_reason, dispatch_manager_tag, ",
        "update_staff, update_time, remark, age_tag, change_type, caller_type, broadband_order_id, ",
        "cross_city_tag, rsync_tag, lock_tag, sys_channel, bus_channel, product_id, lock_reason, ",
        "pool_tag, com_code, post_phone, broadband_cust_name, broadband_pspt_type_code, ",
        "broadband_pspt_no, appoint_date, appoint_date_segment, second_pool_limit_tag, ",
        "post_addr_detail, user_appoint_end_time, user_appoint_start_time, order_province_code, ",
        "order_city_code, enter_msgo_time, callout_times, contact_time, lock_expires_time, ",
        "dn, log_dn, age, sync_tag, link_install_res_tag, link_install_addr, province_name, ",
        "city_name, district_name",
        "from tf_b_order_dispatch",
        "where order_id = #{orderId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="order_no", property="orderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="business_type", property="businessType", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_delivery_intention", property="orderDeliveryIntention", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_creat_time", property="orderCreatTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="goods_name", property="goodsName", jdbcType=JdbcType.VARCHAR),
        @Result(column="province_code_post", property="provinceCodePost", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_code_post", property="cityCodePost", jdbcType=JdbcType.VARCHAR),
        @Result(column="district_code_post", property="districtCodePost", jdbcType=JdbcType.VARCHAR),
        @Result(column="post_addr", property="postAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="dispatch_cmd_cate", property="dispatchCmdCate", jdbcType=JdbcType.TINYINT),
        @Result(column="dispatch_state", property="dispatchState", jdbcType=JdbcType.TINYINT),
        @Result(column="dispatch_obj_type", property="dispatchObjType", jdbcType=JdbcType.TINYINT),
        @Result(column="dispatch_obj_subject", property="dispatchObjSubject", jdbcType=JdbcType.VARCHAR),
        @Result(column="dispatch_obj_tel", property="dispatchObjTel", jdbcType=JdbcType.VARCHAR),
        @Result(column="dispatch_obj_time", property="dispatchObjTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="manual_reason_cate", property="manualReasonCate", jdbcType=JdbcType.TINYINT),
        @Result(column="manual_reason_desc", property="manualReasonDesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="dispatch_recall_reason", property="dispatchRecallReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="dispatch_tag", property="dispatchTag", jdbcType=JdbcType.TINYINT),
        @Result(column="auto_dispatch_grid", property="autoDispatchGrid", jdbcType=JdbcType.VARCHAR),
        @Result(column="auto_dispatch_refer", property="autoDispatchRefer", jdbcType=JdbcType.TINYINT),
        @Result(column="auto_trace", property="autoTrace", jdbcType=JdbcType.VARCHAR),
        @Result(column="map_point", property="mapPoint", jdbcType=JdbcType.VARCHAR),
        @Result(column="timeout_tag", property="timeoutTag", jdbcType=JdbcType.TINYINT),
        @Result(column="order_assign_subject", property="orderAssignSubject", jdbcType=JdbcType.VARCHAR),
        @Result(column="change_reason", property="changeReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="dispatch_manager_tag", property="dispatchManagerTag", jdbcType=JdbcType.CHAR),
        @Result(column="update_staff", property="updateStaff", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="age_tag", property="ageTag", jdbcType=JdbcType.CHAR),
        @Result(column="change_type", property="changeType", jdbcType=JdbcType.VARCHAR),
        @Result(column="caller_type", property="callerType", jdbcType=JdbcType.VARCHAR),
        @Result(column="broadband_order_id", property="broadbandOrderId", jdbcType=JdbcType.BIGINT),
        @Result(column="cross_city_tag", property="crossCityTag", jdbcType=JdbcType.TINYINT),
        @Result(column="rsync_tag", property="rsyncTag", jdbcType=JdbcType.TINYINT),
        @Result(column="lock_tag", property="lockTag", jdbcType=JdbcType.TINYINT),
        @Result(column="sys_channel", property="sysChannel", jdbcType=JdbcType.VARCHAR),
        @Result(column="bus_channel", property="busChannel", jdbcType=JdbcType.VARCHAR),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.VARCHAR),
        @Result(column="lock_reason", property="lockReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="pool_tag", property="poolTag", jdbcType=JdbcType.TINYINT),
        @Result(column="com_code", property="comCode", jdbcType=JdbcType.CHAR),
        @Result(column="post_phone", property="postPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="broadband_cust_name", property="broadbandCustName", jdbcType=JdbcType.VARCHAR),
        @Result(column="broadband_pspt_type_code", property="broadbandPsptTypeCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="broadband_pspt_no", property="broadbandPsptNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="appoint_date", property="appointDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="appoint_date_segment", property="appointDateSegment", jdbcType=JdbcType.TINYINT),
        @Result(column="second_pool_limit_tag", property="secondPoolLimitTag", jdbcType=JdbcType.TINYINT),
        @Result(column="post_addr_detail", property="postAddrDetail", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_appoint_end_time", property="userAppointEndTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_appoint_start_time", property="userAppointStartTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="order_province_code", property="orderProvinceCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_city_code", property="orderCityCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="enter_msgo_time", property="enterMsgoTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="callout_times", property="calloutTimes", jdbcType=JdbcType.VARCHAR),
        @Result(column="contact_time", property="contactTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="lock_expires_time", property="lockExpiresTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="dn", property="dn", jdbcType=JdbcType.INTEGER),
        @Result(column="log_dn", property="logDn", jdbcType=JdbcType.INTEGER),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER),
        @Result(column="sync_tag", property="syncTag", jdbcType=JdbcType.TINYINT),
        @Result(column="link_install_res_tag", property="linkInstallResTag", jdbcType=JdbcType.TINYINT),
        @Result(column="link_install_addr", property="linkInstallAddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="province_name", property="provinceName", jdbcType=JdbcType.VARCHAR),
        @Result(column="city_name", property="cityName", jdbcType=JdbcType.VARCHAR),
        @Result(column="district_name", property="districtName", jdbcType=JdbcType.VARCHAR)
    })
    OrderDispatch selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_order_dispatch
     *
     * @mbg.generated Wed Jun 26 09:42:08 CST 2019
     */
    @UpdateProvider(type=OrderIDispatcSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderDispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_b_order_dispatch
     *
     * @mbg.generated Wed Jun 26 09:42:08 CST 2019
     */
    @Update({
        "update tf_b_order_dispatch",
        "set order_no = #{orderNo,jdbcType=VARCHAR},",
          "business_type = #{businessType,jdbcType=VARCHAR},",
          "order_delivery_intention = #{orderDeliveryIntention,jdbcType=VARCHAR},",
          "order_creat_time = #{orderCreatTime,jdbcType=TIMESTAMP},",
          "goods_name = #{goodsName,jdbcType=VARCHAR},",
          "province_code_post = #{provinceCodePost,jdbcType=VARCHAR},",
          "city_code_post = #{cityCodePost,jdbcType=VARCHAR},",
          "district_code_post = #{districtCodePost,jdbcType=VARCHAR},",
          "post_addr = #{postAddr,jdbcType=VARCHAR},",
          "dispatch_cmd_cate = #{dispatchCmdCate,jdbcType=TINYINT},",
          "dispatch_state = #{dispatchState,jdbcType=TINYINT},",
          "dispatch_obj_type = #{dispatchObjType,jdbcType=TINYINT},",
          "dispatch_obj_subject = #{dispatchObjSubject,jdbcType=VARCHAR},",
          "dispatch_obj_tel = #{dispatchObjTel,jdbcType=VARCHAR},",
          "dispatch_obj_time = #{dispatchObjTime,jdbcType=TIMESTAMP},",
          "manual_reason_cate = #{manualReasonCate,jdbcType=TINYINT},",
          "manual_reason_desc = #{manualReasonDesc,jdbcType=VARCHAR},",
          "dispatch_recall_reason = #{dispatchRecallReason,jdbcType=VARCHAR},",
          "dispatch_tag = #{dispatchTag,jdbcType=TINYINT},",
          "auto_dispatch_grid = #{autoDispatchGrid,jdbcType=VARCHAR},",
          "auto_dispatch_refer = #{autoDispatchRefer,jdbcType=TINYINT},",
          "auto_trace = #{autoTrace,jdbcType=VARCHAR},",
          "map_point = #{mapPoint,jdbcType=VARCHAR},",
          "timeout_tag = #{timeoutTag,jdbcType=TINYINT},",
          "order_assign_subject = #{orderAssignSubject,jdbcType=VARCHAR},",
          "change_reason = #{changeReason,jdbcType=VARCHAR},",
          "dispatch_manager_tag = #{dispatchManagerTag,jdbcType=CHAR},",
          "update_staff = #{updateStaff,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "age_tag = #{ageTag,jdbcType=CHAR},",
          "change_type = #{changeType,jdbcType=VARCHAR},",
          "caller_type = #{callerType,jdbcType=VARCHAR},",
          "broadband_order_id = #{broadbandOrderId,jdbcType=BIGINT},",
          "cross_city_tag = #{crossCityTag,jdbcType=TINYINT},",
          "rsync_tag = #{rsyncTag,jdbcType=TINYINT},",
          "lock_tag = #{lockTag,jdbcType=TINYINT},",
          "sys_channel = #{sysChannel,jdbcType=VARCHAR},",
          "bus_channel = #{busChannel,jdbcType=VARCHAR},",
          "product_id = #{productId,jdbcType=VARCHAR},",
          "lock_reason = #{lockReason,jdbcType=VARCHAR},",
          "pool_tag = #{poolTag,jdbcType=TINYINT},",
          "com_code = #{comCode,jdbcType=CHAR},",
          "post_phone = #{postPhone,jdbcType=VARCHAR},",
          "broadband_cust_name = #{broadbandCustName,jdbcType=VARCHAR},",
          "broadband_pspt_type_code = #{broadbandPsptTypeCode,jdbcType=VARCHAR},",
          "broadband_pspt_no = #{broadbandPsptNo,jdbcType=VARCHAR},",
          "appoint_date = #{appointDate,jdbcType=TIMESTAMP},",
          "appoint_date_segment = #{appointDateSegment,jdbcType=TINYINT},",
          "second_pool_limit_tag = #{secondPoolLimitTag,jdbcType=TINYINT},",
          "post_addr_detail = #{postAddrDetail,jdbcType=VARCHAR},",
          "user_appoint_end_time = #{userAppointEndTime,jdbcType=TIMESTAMP},",
          "user_appoint_start_time = #{userAppointStartTime,jdbcType=TIMESTAMP},",
          "order_province_code = #{orderProvinceCode,jdbcType=VARCHAR},",
          "order_city_code = #{orderCityCode,jdbcType=VARCHAR},",
          "enter_msgo_time = #{enterMsgoTime,jdbcType=TIMESTAMP},",
          "callout_times = #{calloutTimes,jdbcType=VARCHAR},",
          "contact_time = #{contactTime,jdbcType=TIMESTAMP},",
          "lock_expires_time = #{lockExpiresTime,jdbcType=TIMESTAMP},",
          "dn = #{dn,jdbcType=INTEGER},",
          "log_dn = #{logDn,jdbcType=INTEGER},",
          "age = #{age,jdbcType=INTEGER},",
          "sync_tag = #{syncTag,jdbcType=TINYINT},",
          "link_install_res_tag = #{linkInstallResTag,jdbcType=TINYINT},",
          "link_install_addr = #{linkInstallAddr,jdbcType=VARCHAR},",
          "province_name = #{provinceName,jdbcType=VARCHAR},",
          "city_name = #{cityName,jdbcType=VARCHAR},",
          "district_name = #{districtName,jdbcType=VARCHAR}",
        "where order_id = #{orderId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OrderDispatch record);
    
    class OrderIDispatcSqlProvider {

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tf_b_order_dispatch
         *
         * @mbg.generated Wed Jun 26 09:42:08 CST 2019
         */
        public String insertSelective(OrderDispatch record) {
            SQL sql = new SQL();
            sql.INSERT_INTO("tf_b_order_dispatch");
            
            if (record.getOrderId() != null) {
                sql.VALUES("order_id", "#{orderId,jdbcType=BIGINT}");
            }
            
            if (record.getOrderNo() != null) {
                sql.VALUES("order_no", "#{orderNo,jdbcType=VARCHAR}");
            }
            
            if (record.getBusinessType() != null) {
                sql.VALUES("business_type", "#{businessType,jdbcType=VARCHAR}");
            }
            
            if (record.getOrderDeliveryIntention() != null) {
                sql.VALUES("order_delivery_intention", "#{orderDeliveryIntention,jdbcType=VARCHAR}");
            }
            
            if (record.getOrderCreatTime() != null) {
                sql.VALUES("order_creat_time", "#{orderCreatTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getGoodsName() != null) {
                sql.VALUES("goods_name", "#{goodsName,jdbcType=VARCHAR}");
            }
            
            if (record.getProvinceCodePost() != null) {
                sql.VALUES("province_code_post", "#{provinceCodePost,jdbcType=VARCHAR}");
            }
            
            if (record.getCityCodePost() != null) {
                sql.VALUES("city_code_post", "#{cityCodePost,jdbcType=VARCHAR}");
            }
            
            if (record.getDistrictCodePost() != null) {
                sql.VALUES("district_code_post", "#{districtCodePost,jdbcType=VARCHAR}");
            }
            
            if (record.getPostAddr() != null) {
                sql.VALUES("post_addr", "#{postAddr,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchCmdCate() != null) {
                sql.VALUES("dispatch_cmd_cate", "#{dispatchCmdCate,jdbcType=TINYINT}");
            }
            
            if (record.getDispatchState() != null) {
                sql.VALUES("dispatch_state", "#{dispatchState,jdbcType=TINYINT}");
            }
            
            if (record.getDispatchObjType() != null) {
                sql.VALUES("dispatch_obj_type", "#{dispatchObjType,jdbcType=TINYINT}");
            }
            
            if (record.getDispatchObjSubject() != null) {
                sql.VALUES("dispatch_obj_subject", "#{dispatchObjSubject,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchObjTel() != null) {
                sql.VALUES("dispatch_obj_tel", "#{dispatchObjTel,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchObjTime() != null) {
                sql.VALUES("dispatch_obj_time", "#{dispatchObjTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getManualReasonCate() != null) {
                sql.VALUES("manual_reason_cate", "#{manualReasonCate,jdbcType=TINYINT}");
            }
            
            if (record.getManualReasonDesc() != null) {
                sql.VALUES("manual_reason_desc", "#{manualReasonDesc,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchRecallReason() != null) {
                sql.VALUES("dispatch_recall_reason", "#{dispatchRecallReason,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchTag() != null) {
                sql.VALUES("dispatch_tag", "#{dispatchTag,jdbcType=TINYINT}");
            }
            
            if (record.getAutoDispatchGrid() != null) {
                sql.VALUES("auto_dispatch_grid", "#{autoDispatchGrid,jdbcType=VARCHAR}");
            }
            
            if (record.getAutoDispatchRefer() != null) {
                sql.VALUES("auto_dispatch_refer", "#{autoDispatchRefer,jdbcType=TINYINT}");
            }
            
            if (record.getAutoTrace() != null) {
                sql.VALUES("auto_trace", "#{autoTrace,jdbcType=VARCHAR}");
            }
            
            if (record.getMapPoint() != null) {
                sql.VALUES("map_point", "#{mapPoint,jdbcType=VARCHAR}");
            }
            
            if (record.getTimeoutTag() != null) {
                sql.VALUES("timeout_tag", "#{timeoutTag,jdbcType=TINYINT}");
            }
            
            if (record.getOrderAssignSubject() != null) {
                sql.VALUES("order_assign_subject", "#{orderAssignSubject,jdbcType=VARCHAR}");
            }
            
            if (record.getChangeReason() != null) {
                sql.VALUES("change_reason", "#{changeReason,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchManagerTag() != null) {
                sql.VALUES("dispatch_manager_tag", "#{dispatchManagerTag,jdbcType=CHAR}");
            }
            
            if (record.getUpdateStaff() != null) {
                sql.VALUES("update_staff", "#{updateStaff,jdbcType=VARCHAR}");
            }
            
            if (record.getUpdateTime() != null) {
                sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getRemark() != null) {
                sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
            }
            
            if (record.getAgeTag() != null) {
                sql.VALUES("age_tag", "#{ageTag,jdbcType=CHAR}");
            }
            
            if (record.getChangeType() != null) {
                sql.VALUES("change_type", "#{changeType,jdbcType=VARCHAR}");
            }
            
            if (record.getCallerType() != null) {
                sql.VALUES("caller_type", "#{callerType,jdbcType=VARCHAR}");
            }
            
            if (record.getBroadbandOrderId() != null) {
                sql.VALUES("broadband_order_id", "#{broadbandOrderId,jdbcType=BIGINT}");
            }
            
            if (record.getCrossCityTag() != null) {
                sql.VALUES("cross_city_tag", "#{crossCityTag,jdbcType=TINYINT}");
            }
            
            if (record.getRsyncTag() != null) {
                sql.VALUES("rsync_tag", "#{rsyncTag,jdbcType=TINYINT}");
            }
            
            if (record.getLockTag() != null) {
                sql.VALUES("lock_tag", "#{lockTag,jdbcType=TINYINT}");
            }
            
            if (record.getSysChannel() != null) {
                sql.VALUES("sys_channel", "#{sysChannel,jdbcType=VARCHAR}");
            }
            
            if (record.getBusChannel() != null) {
                sql.VALUES("bus_channel", "#{busChannel,jdbcType=VARCHAR}");
            }
            
            if (record.getProductId() != null) {
                sql.VALUES("product_id", "#{productId,jdbcType=VARCHAR}");
            }
            
            if (record.getLockReason() != null) {
                sql.VALUES("lock_reason", "#{lockReason,jdbcType=VARCHAR}");
            }
            
            if (record.getPoolTag() != null) {
                sql.VALUES("pool_tag", "#{poolTag,jdbcType=TINYINT}");
            }
            
            if (record.getComCode() != null) {
                sql.VALUES("com_code", "#{comCode,jdbcType=CHAR}");
            }
            
            if (record.getPostPhone() != null) {
                sql.VALUES("post_phone", "#{postPhone,jdbcType=VARCHAR}");
            }
            
            if (record.getBroadbandCustName() != null) {
                sql.VALUES("broadband_cust_name", "#{broadbandCustName,jdbcType=VARCHAR}");
            }
            
            if (record.getBroadbandPsptTypeCode() != null) {
                sql.VALUES("broadband_pspt_type_code", "#{broadbandPsptTypeCode,jdbcType=VARCHAR}");
            }
            
            if (record.getBroadbandPsptNo() != null) {
                sql.VALUES("broadband_pspt_no", "#{broadbandPsptNo,jdbcType=VARCHAR}");
            }
            
            if (record.getAppointDate() != null) {
                sql.VALUES("appoint_date", "#{appointDate,jdbcType=TIMESTAMP}");
            }
            
            if (record.getAppointDateSegment() != null) {
                sql.VALUES("appoint_date_segment", "#{appointDateSegment,jdbcType=TINYINT}");
            }
            
            if (record.getSecondPoolLimitTag() != null) {
                sql.VALUES("second_pool_limit_tag", "#{secondPoolLimitTag,jdbcType=TINYINT}");
            }
            
            if (record.getPostAddrDetail() != null) {
                sql.VALUES("post_addr_detail", "#{postAddrDetail,jdbcType=VARCHAR}");
            }
            
            if (record.getUserAppointEndTime() != null) {
                sql.VALUES("user_appoint_end_time", "#{userAppointEndTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getUserAppointStartTime() != null) {
                sql.VALUES("user_appoint_start_time", "#{userAppointStartTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getOrderProvinceCode() != null) {
                sql.VALUES("order_province_code", "#{orderProvinceCode,jdbcType=VARCHAR}");
            }
            
            if (record.getOrderCityCode() != null) {
                sql.VALUES("order_city_code", "#{orderCityCode,jdbcType=VARCHAR}");
            }
            
            if (record.getEnterMsgoTime() != null) {
                sql.VALUES("enter_msgo_time", "#{enterMsgoTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getCalloutTimes() != null) {
                sql.VALUES("callout_times", "#{calloutTimes,jdbcType=VARCHAR}");
            }
            
            if (record.getContactTime() != null) {
                sql.VALUES("contact_time", "#{contactTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getLockExpiresTime() != null) {
                sql.VALUES("lock_expires_time", "#{lockExpiresTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getDn() != null) {
                sql.VALUES("dn", "#{dn,jdbcType=INTEGER}");
            }
            
            if (record.getLogDn() != null) {
                sql.VALUES("log_dn", "#{logDn,jdbcType=INTEGER}");
            }
            
            if (record.getAge() != null) {
                sql.VALUES("age", "#{age,jdbcType=INTEGER}");
            }
            
            if (record.getSyncTag() != null) {
                sql.VALUES("sync_tag", "#{syncTag,jdbcType=TINYINT}");
            }
            
            if (record.getLinkInstallResTag() != null) {
                sql.VALUES("link_install_res_tag", "#{linkInstallResTag,jdbcType=TINYINT}");
            }
            
            if (record.getLinkInstallAddr() != null) {
                sql.VALUES("link_install_addr", "#{linkInstallAddr,jdbcType=VARCHAR}");
            }
            
            if (record.getProvinceName() != null) {
                sql.VALUES("province_name", "#{provinceName,jdbcType=VARCHAR}");
            }
            
            if (record.getCityName() != null) {
                sql.VALUES("city_name", "#{cityName,jdbcType=VARCHAR}");
            }
            
            if (record.getDistrictName() != null) {
                sql.VALUES("district_name", "#{districtName,jdbcType=VARCHAR}");
            }
            
            return sql.toString();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table tf_b_order_dispatch
         *
         * @mbg.generated Wed Jun 26 09:42:08 CST 2019
         */
        public String updateByPrimaryKeySelective(OrderDispatch record) {
            SQL sql = new SQL();
            sql.UPDATE("tf_b_order_dispatch");
            
            if (record.getOrderNo() != null) {
                sql.SET("order_no = #{orderNo,jdbcType=VARCHAR}");
            }
            
            if (record.getBusinessType() != null) {
                sql.SET("business_type = #{businessType,jdbcType=VARCHAR}");
            }
            
            if (record.getOrderDeliveryIntention() != null) {
                sql.SET("order_delivery_intention = #{orderDeliveryIntention,jdbcType=VARCHAR}");
            }
            
            if (record.getOrderCreatTime() != null) {
                sql.SET("order_creat_time = #{orderCreatTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getGoodsName() != null) {
                sql.SET("goods_name = #{goodsName,jdbcType=VARCHAR}");
            }
            
            if (record.getProvinceCodePost() != null) {
                sql.SET("province_code_post = #{provinceCodePost,jdbcType=VARCHAR}");
            }
            
            if (record.getCityCodePost() != null) {
                sql.SET("city_code_post = #{cityCodePost,jdbcType=VARCHAR}");
            }
            
            if (record.getDistrictCodePost() != null) {
                sql.SET("district_code_post = #{districtCodePost,jdbcType=VARCHAR}");
            }
            
            if (record.getPostAddr() != null) {
                sql.SET("post_addr = #{postAddr,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchCmdCate() != null) {
                sql.SET("dispatch_cmd_cate = #{dispatchCmdCate,jdbcType=TINYINT}");
            }
            
            if (record.getDispatchState() != null) {
                sql.SET("dispatch_state = #{dispatchState,jdbcType=TINYINT}");
            }
            
            if (record.getDispatchObjType() != null) {
                sql.SET("dispatch_obj_type = #{dispatchObjType,jdbcType=TINYINT}");
            }
            
            if (record.getDispatchObjSubject() != null) {
                sql.SET("dispatch_obj_subject = #{dispatchObjSubject,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchObjTel() != null) {
                sql.SET("dispatch_obj_tel = #{dispatchObjTel,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchObjTime() != null) {
                sql.SET("dispatch_obj_time = #{dispatchObjTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getManualReasonCate() != null) {
                sql.SET("manual_reason_cate = #{manualReasonCate,jdbcType=TINYINT}");
            }
            
            if (record.getManualReasonDesc() != null) {
                sql.SET("manual_reason_desc = #{manualReasonDesc,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchRecallReason() != null) {
                sql.SET("dispatch_recall_reason = #{dispatchRecallReason,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchTag() != null) {
                sql.SET("dispatch_tag = #{dispatchTag,jdbcType=TINYINT}");
            }
            
            if (record.getAutoDispatchGrid() != null) {
                sql.SET("auto_dispatch_grid = #{autoDispatchGrid,jdbcType=VARCHAR}");
            }
            
            if (record.getAutoDispatchRefer() != null) {
                sql.SET("auto_dispatch_refer = #{autoDispatchRefer,jdbcType=TINYINT}");
            }
            
            if (record.getAutoTrace() != null) {
                sql.SET("auto_trace = #{autoTrace,jdbcType=VARCHAR}");
            }
            
            if (record.getMapPoint() != null) {
                sql.SET("map_point = #{mapPoint,jdbcType=VARCHAR}");
            }
            
            if (record.getTimeoutTag() != null) {
                sql.SET("timeout_tag = #{timeoutTag,jdbcType=TINYINT}");
            }
            
            if (record.getOrderAssignSubject() != null) {
                sql.SET("order_assign_subject = #{orderAssignSubject,jdbcType=VARCHAR}");
            }
            
            if (record.getChangeReason() != null) {
                sql.SET("change_reason = #{changeReason,jdbcType=VARCHAR}");
            }
            
            if (record.getDispatchManagerTag() != null) {
                sql.SET("dispatch_manager_tag = #{dispatchManagerTag,jdbcType=CHAR}");
            }
            
            if (record.getUpdateStaff() != null) {
                sql.SET("update_staff = #{updateStaff,jdbcType=VARCHAR}");
            }
            
            if (record.getUpdateTime() != null) {
                sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getRemark() != null) {
                sql.SET("remark = #{remark,jdbcType=VARCHAR}");
            }
            
            if (record.getAgeTag() != null) {
                sql.SET("age_tag = #{ageTag,jdbcType=CHAR}");
            }
            
            if (record.getChangeType() != null) {
                sql.SET("change_type = #{changeType,jdbcType=VARCHAR}");
            }
            
            if (record.getCallerType() != null) {
                sql.SET("caller_type = #{callerType,jdbcType=VARCHAR}");
            }
            
            if (record.getBroadbandOrderId() != null) {
                sql.SET("broadband_order_id = #{broadbandOrderId,jdbcType=BIGINT}");
            }
            
            if (record.getCrossCityTag() != null) {
                sql.SET("cross_city_tag = #{crossCityTag,jdbcType=TINYINT}");
            }
            
            if (record.getRsyncTag() != null) {
                sql.SET("rsync_tag = #{rsyncTag,jdbcType=TINYINT}");
            }
            
            if (record.getLockTag() != null) {
                sql.SET("lock_tag = #{lockTag,jdbcType=TINYINT}");
            }
            
            if (record.getSysChannel() != null) {
                sql.SET("sys_channel = #{sysChannel,jdbcType=VARCHAR}");
            }
            
            if (record.getBusChannel() != null) {
                sql.SET("bus_channel = #{busChannel,jdbcType=VARCHAR}");
            }
            
            if (record.getProductId() != null) {
                sql.SET("product_id = #{productId,jdbcType=VARCHAR}");
            }
            
            if (record.getLockReason() != null) {
                sql.SET("lock_reason = #{lockReason,jdbcType=VARCHAR}");
            }
            
            if (record.getPoolTag() != null) {
                sql.SET("pool_tag = #{poolTag,jdbcType=TINYINT}");
            }
            
            if (record.getComCode() != null) {
                sql.SET("com_code = #{comCode,jdbcType=CHAR}");
            }
            
            if (record.getPostPhone() != null) {
                sql.SET("post_phone = #{postPhone,jdbcType=VARCHAR}");
            }
            
            if (record.getBroadbandCustName() != null) {
                sql.SET("broadband_cust_name = #{broadbandCustName,jdbcType=VARCHAR}");
            }
            
            if (record.getBroadbandPsptTypeCode() != null) {
                sql.SET("broadband_pspt_type_code = #{broadbandPsptTypeCode,jdbcType=VARCHAR}");
            }
            
            if (record.getBroadbandPsptNo() != null) {
                sql.SET("broadband_pspt_no = #{broadbandPsptNo,jdbcType=VARCHAR}");
            }
            
            if (record.getAppointDate() != null) {
                sql.SET("appoint_date = #{appointDate,jdbcType=TIMESTAMP}");
            }
            
            if (record.getAppointDateSegment() != null) {
                sql.SET("appoint_date_segment = #{appointDateSegment,jdbcType=TINYINT}");
            }
            
            if (record.getSecondPoolLimitTag() != null) {
                sql.SET("second_pool_limit_tag = #{secondPoolLimitTag,jdbcType=TINYINT}");
            }
            
            if (record.getPostAddrDetail() != null) {
                sql.SET("post_addr_detail = #{postAddrDetail,jdbcType=VARCHAR}");
            }
            
            if (record.getUserAppointEndTime() != null) {
                sql.SET("user_appoint_end_time = #{userAppointEndTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getUserAppointStartTime() != null) {
                sql.SET("user_appoint_start_time = #{userAppointStartTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getOrderProvinceCode() != null) {
                sql.SET("order_province_code = #{orderProvinceCode,jdbcType=VARCHAR}");
            }
            
            if (record.getOrderCityCode() != null) {
                sql.SET("order_city_code = #{orderCityCode,jdbcType=VARCHAR}");
            }
            
            if (record.getEnterMsgoTime() != null) {
                sql.SET("enter_msgo_time = #{enterMsgoTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getCalloutTimes() != null) {
                sql.SET("callout_times = #{calloutTimes,jdbcType=VARCHAR}");
            }
            
            if (record.getContactTime() != null) {
                sql.SET("contact_time = #{contactTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getLockExpiresTime() != null) {
                sql.SET("lock_expires_time = #{lockExpiresTime,jdbcType=TIMESTAMP}");
            }
            
            if (record.getDn() != null) {
                sql.SET("dn = #{dn,jdbcType=INTEGER}");
            }
            
            if (record.getLogDn() != null) {
                sql.SET("log_dn = #{logDn,jdbcType=INTEGER}");
            }
            
            if (record.getAge() != null) {
                sql.SET("age = #{age,jdbcType=INTEGER}");
            }
            
            if (record.getSyncTag() != null) {
                sql.SET("sync_tag = #{syncTag,jdbcType=TINYINT}");
            }
            
            if (record.getLinkInstallResTag() != null) {
                sql.SET("link_install_res_tag = #{linkInstallResTag,jdbcType=TINYINT}");
            }
            
            if (record.getLinkInstallAddr() != null) {
                sql.SET("link_install_addr = #{linkInstallAddr,jdbcType=VARCHAR}");
            }
            
            if (record.getProvinceName() != null) {
                sql.SET("province_name = #{provinceName,jdbcType=VARCHAR}");
            }
            
            if (record.getCityName() != null) {
                sql.SET("city_name = #{cityName,jdbcType=VARCHAR}");
            }
            
            if (record.getDistrictName() != null) {
                sql.SET("district_name = #{districtName,jdbcType=VARCHAR}");
            }
            
            sql.WHERE("order_id = #{orderId,jdbcType=BIGINT}");
            
            return sql.toString();
        }
    }
    
}