/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 80015
Source Host           : localhost:3306
Source Database       : ecsorder

Target Server Type    : MYSQL
Target Server Version : 80015
File Encoding         : 65001

Date: 2019-07-12 11:03:08
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for tf_b_order_index
-- ----------------------------
DROP TABLE IF EXISTS `tf_b_order_index`;
CREATE TABLE `tf_b_order_index` (
  `order_id` bigint(20) NOT NULL COMMENT '订单标识',
  `order_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单NO',
  `staff_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '当前订单分配员工',
  `order_state` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '00:成功关闭;A0:待支付;AX:待支付退单;B0:待分配;BX:待分配退单;C0:待处理;C1:处理中;CA:待开户;CX:订单处理退单;CZ:待拣货;D0:待发货;D1:发货中;DX:发货退单;E0:物流在途;F0:未签收;F1:已签收;FX:客户拒收退单;H0:待自动审单;HF:待人工审单;HX:审单退单;L0:待波次拣货;L1:波次拣货中;M0:待质检;P0:待波次匹配;SX:系统退单;T0:待流程匹配;N0:分拣配货;N5:配货交接;X0:京东',
  `business_type` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '01:普通订单;02:空中入网订单;03:体验卡订单;04:靓号专区跳转订单;05:白条订单;06:大区商品订单',
  `province_code` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '省份编码',
  `city_code` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '地市编码',
  `process_merchant_id` bigint(20) DEFAULT NULL,
  `goods_id` bigint(20) DEFAULT NULL COMMENT '商品标识',
  `goods_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商品名称',
  `tmpl_id` bigint(20) DEFAULT NULL COMMENT '模板标识',
  `pspt_type_code` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '证件类型',
  `pspt_addr` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '证件地址',
  `phone_number` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '0' COMMENT '主卡订购号码',
  `pspt_no` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '证件号码',
  `real_name_type` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `province_code_post` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `city_code_post` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `district_code_post` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `mobile_phone` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `post_addr` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `king_broad_number` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '王卡关联宽带的宽带订单号',
  `audit_tag` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '打标用',
  `seller_remark` varchar(900) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '卖家留言',
  `deliver_company_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '物流公司COde',
  `checkpass` bigint(20) NOT NULL DEFAULT '0' COMMENT '审单通过标志',
  `ex_remark` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '异常详情',
  `mashanggou` bigint(20) NOT NULL DEFAULT '0' COMMENT '码上购标记 0物流1上门2自提3码上购智能派单',
  `evil_level` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '腾讯接口返回信用值',
  `talk_time` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '调用时间',
  `king_ground_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '线上购标记',
  `ex_code` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '异常code',
  `mobile_product_id` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '联系电话的ProdectID',
  `cust_ip` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '客户下单IP',
  `product_id` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '产品ID',
  `active_state` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '空：默认为空，无需激活 0：待激活 1：已激活 2：激活失败',
  `selfget_addr_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '自提厅名称',
  `selfget_addr` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `amount_received` bigint(20) DEFAULT NULL COMMENT '实收金额',
  `claim_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '领用标记 0：未指定  1：分配 2：领用',
  `income_money` bigint(20) DEFAULT NULL COMMENT '实际已经收款金额',
  `order_total_money` bigint(20) DEFAULT NULL COMMENT '订单总价',
  `pay_type` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '01在线支付 02货到付款 03线下现场付款 05白条支付 06计费后收',
  `deliver_type_code` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '01 快递 02 不需要配送 03 自提（TF_B_ORDER_SELFFETCH_RELE.SELF_TYPE查看是电商自提还是营业厅自提） 04 上来联通自提 05 自行配送 06 联通营业厅自提 07 上门激活',
  `cust_remark` varchar(900) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '客户备注',
  `conn_channel` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '还是订单来源',
  `order_from` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单来源',
  `later_active_flag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '空或0：不走实名制后激活 1：走实名制后激活',
  `sub_count` smallint(2) NOT NULL DEFAULT '0' COMMENT '如果是0 ，那就没有副卡，有副卡就写上数量，默认0',
  `mult_type` tinyint(2) DEFAULT NULL COMMENT '老带新1，新带新标志2,普通卡0,不为空',
  `terminal_brand` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '终端品牌',
  `terminal_model` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '终端型号',
  `terminal_color` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '终端颜色',
  `order_type` tinyint(2) DEFAULT NULL COMMENT '2I为0,2C为1,2E为2',
  `cancel_tag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '0-未退单（默认）1-已退单 A-申请退单 B-申请退单通过 C-正在退单 D-退单失败 F-退单驳回 L-锁定 H-处理失败 N-压单订单不退款',
  `pay_state` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '0-未支付（默认） 1-已支付 2-已退款 A-申请退款 B-线下退款 D-退款失败',
  `tid` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `spec_remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '拒收的附加备注',
  `applicant_phone` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '申请人电话',
  `original_state` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '处理前订单状态',
  `user_tag` tinyint(2) DEFAULT NULL COMMENT '1：新用户 2：老用户',
  `delay_tag` tinyint(2) DEFAULT NULL COMMENT '0/空：不压单',
  `pay_money` bigint(11) DEFAULT NULL,
  `pay_remark` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付备注',
  `payorg_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付机构名称',
  `paychnl_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付渠道名称',
  `league_name` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `card_cancel` tinyint(2) NOT NULL DEFAULT '0' COMMENT '0正常，1申请退单',
  `topay_money` bigint(20) DEFAULT NULL COMMENT '应收总金额',
  `referrer_phone` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '推荐人手机号',
  `account_flag` tinyint(2) DEFAULT NULL COMMENT '1-是预开户 2-正式提交开户（上网卡无此状态）',
  `num_expire_time` datetime DEFAULT NULL COMMENT '号码预占到期时间',
  `attr_val_name` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `receiver_name` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL COMMENT '下单时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `cust_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '客户姓名',
  `order_time` datetime DEFAULT NULL,
  `applicant_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '申请人姓名',
  `referrer_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '推荐人姓名',
  `dn` int(6) NOT NULL COMMENT '路由ID',
  `log_dn` int(6) NOT NULL COMMENT '路由ID',
  `deliver_date_type` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '送货时间类型 01：不限时间 02：只工作日 03：只有双休日、节假日 04：不送货',
  `tendency_channel_two` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '二级渠道',
  `kingcard_channel_two` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '二级渠道',
  `phone_excode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '审单上传照片状态筛选码',
  `cross_city` tinyint(2) NOT NULL DEFAULT '0' COMMENT '0表示本地订单 1表示异地订单',
  `coupon_money` bigint(11) DEFAULT NULL COMMENT '优惠总金额',
  `mashanggou_back_state` tinyint(2) NOT NULL DEFAULT '0' COMMENT '0：正常订单 1: 码上购返回，转为物流方式  2:码上购返申请转为审单状态',
  `openacc_state` tinyint(2) NOT NULL DEFAULT '0' COMMENT '0未开户，1正在开户',
  `tendency_channel` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `tendency_channel_three` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '三级渠道',
  `kingcard_channel` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `kingcard_channel_three` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '三级渠道',
  `iccid` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '卡号',
  `otter_synchronize_pk` bigint(20) DEFAULT NULL COMMENT 'otter同步主键',
  `alitrip_tag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0',
  `tb_fz` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `mult_code` tinyint(2) DEFAULT NULL COMMENT '0:非多号码订单 1:新带新2:亲情卡 3：老带新 5：老带新一带一',
  `verify_excode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT ' 审单标记异常筛选项',
  `post_tag` tinyint(2) DEFAULT NULL COMMENT '0：不邮寄 1：单一地址邮寄 2：多地址邮寄（拆分邮寄）',
  `phone_state` tinyint(2) NOT NULL DEFAULT '3' COMMENT '收件人联系电话状态 0：不可达, 1：可达 , 3：未知（未查询到）',
  `age` int(4) DEFAULT NULL,
  `chunicom` tinyint(2) NOT NULL DEFAULT '0' COMMENT '0代表异网用户，1代表本网用户',
  `mobile_channel` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付宝芝麻信息',
  `lgts_order` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '物流发货单号',
  PRIMARY KEY (`order_id`,`province_code`),
  KEY `order_no` (`order_no`) USING BTREE,
  KEY `staff_id` (`staff_id`) USING BTREE,
  KEY `order_state` (`order_state`) USING BTREE,
  KEY `city_code` (`city_code`) USING BTREE,
  KEY `create_time` (`create_time`) USING BTREE,
  KEY `order_time` (`order_time`) USING BTREE,
  KEY `phone_number` (`phone_number`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
