/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 80015
Source Host           : localhost:3306
Source Database       : ecsorder

Target Server Type    : MYSQL
Target Server Version : 80015
File Encoding         : 65001

Date: 2019-07-12 11:03:52
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for tf_b_order
-- ----------------------------
DROP TABLE IF EXISTS `tf_b_order`;
CREATE TABLE `tf_b_order` (
  `province_code` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '省份编码',
  `order_id` bigint(20) NOT NULL COMMENT '订单ID',
  `order_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单NO',
  `phone_number` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0' COMMENT '主卡订购号码',
  `merchant_id` int(8) DEFAULT NULL COMMENT '订单归属商户ID',
  `staff_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '当前订单分配员工',
  `claim_flag` varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '领用标记 0：未指定  1：分配 2：领用 ',
  `pay_type` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '01在线支付 02货到付款 03线下现场付款 05白条支付 06计费后收',
  `pay_way` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付方式',
  `pay_state` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '0-未支付（默认） 1-已支付 2-已退款 A-申请退款 B-线下退款 D-退款失败',
  `goods_id` bigint(12) DEFAULT NULL COMMENT '商品标识',
  `goods_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商品名称',
  `tmpl_id` bigint(20) DEFAULT NULL COMMENT '模板标识',
  `product_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '产品名',
  `product_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '产品ID',
  `first_month_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '首月套餐类型',
  `city_code` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '地市编码',
  `cancel_tag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '0-未退单（默认）1-已退单 A-申请退单 B-申请退单通过 C-正在退单 D-退单失败 F-退单驳回 L-锁定 H-处理失败 N-压单订单不退款',
  `deliver_type_code` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '01 快递 02 不需要配送 03 自提（TF_B_ORDER_SELFFETCH_RELE.SELF_TYPE查看是电商自提还是营业厅自提） 04 上来联通自提 05 自行配送 06 联通营业厅自提 07 上门激活',
  `order_state` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '00:成功关闭;A0:待支付;AX:待支付退单;B0:待分配;BX:待分配退单;C0:待处理;C1:处理中;CA:待开户;CX:订单处理退单;CZ:待拣货;D0:待发货;D1:发货中;DX:发货退单;E0:物流在途;F0:未签收;F1:已签收;FX:客户拒收退单;H0:待自动审单;HF:待人工审单;HX:审单退单;L0:待波次拣货;L1:波次拣货中;M0:待质检;P0:待波次匹配;SX:系统退单;T0:待流程匹配;N0:分拣配货;N5:配货交接;X0:京东',
  `business_type` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '01:普通订单;02:空中入网订单;03:体验卡订单;04:靓号专区跳转订单;05:白条订单;06:大区商品订单 ',
  `income_money` decimal(20,0) DEFAULT NULL COMMENT '实际已经收款金额',
  `post_fee` decimal(20,0) DEFAULT NULL COMMENT '邮寄费用',
  `coupon_money` decimal(20,0) DEFAULT NULL COMMENT '优惠总金额',
  `order_total_money` decimal(20,0) DEFAULT NULL COMMENT '订单总价',
  `iccid` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '卡号',
  `cust_remark` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '客户备注',
  `selfget_addr_id` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '自提厅ID',
  `selfget_addr_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '自提厅名称',
  `ex_code` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '异常code',
  `ex_remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '异常详情',
  `order_from` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单来源',
  `card_cancel` tinyint(2) NOT NULL DEFAULT '0' COMMENT '默认是无退单状态0，副卡或者主卡有退单为1',
  `sub_count` smallint(2) NOT NULL DEFAULT '0' COMMENT '如果是0 ，那就没有副卡，有副卡就写上数量，默认0',
  `king_broad_number` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '宽带标志',
  `topay_money` bigint(11) DEFAULT NULL COMMENT '应收总金额',
  `mult_type` tinyint(2) DEFAULT NULL COMMENT '老带新1，新带新标志2,普通卡0,不为空',
  `order_type` tinyint(2) DEFAULT NULL COMMENT '2I为0,2C为1,2E为2',
  `mall_active` tinyint(2) DEFAULT NULL COMMENT '是否老商城激活,1是，0否',
  `wf_id` bigint(16) DEFAULT NULL COMMENT '流程ID',
  `rule_id` bigint(16) DEFAULT NULL COMMENT '规则ID',
  `audit_tag` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '新入网月份',
  `additional_product_package` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '附加产品包',
  `optional_product_package` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '可选产品包',
  `amount_recevable` bigint(11) DEFAULT NULL COMMENT '应收金额',
  `amount_derate` bigint(11) DEFAULT NULL COMMENT '减免金额 = 应收金额-实收金额',
  `amount_received` bigint(11) DEFAULT NULL COMMENT '实收金额',
  `goods_inst_id` bigint(16) DEFAULT NULL COMMENT '增加商品条码主要的目的是为了唯一识别商品',
  `tencent_channel` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单渠道（腾讯）',
  `king_ground_flag` tinyint(2) DEFAULT NULL COMMENT '线上购标记',
  `henan_channel_from` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '订单渠道（貌似河南的）',
  `conn_channel` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '还是订单来源',
  `checkpass` smallint(2) NOT NULL DEFAULT '0' COMMENT '审单通过标志',
  `cust_ip` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '客户下单IP',
  `original_price` bigint(11) DEFAULT NULL COMMENT '订单原价',
  `terminal_brand` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '终端品牌',
  `terminal_model` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '终端型号',
  `terminal_color` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '终端颜色',
  `later_active_flag` tinyint(2) DEFAULT NULL COMMENT '空或0：不走实名制后激活 1：走实名制后激活',
  `manual_check` tinyint(2) DEFAULT NULL COMMENT '转人工激活标识 0:未转人工，1:已转人工，默认0',
  `active_remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '人工激活备注',
  `front_check` tinyint(2) DEFAULT NULL COMMENT '证件照正面校验结果，0：不通过，1：通过，默认0',
  `back_check` tinyint(2) DEFAULT NULL COMMENT '证件照反面校验结果，0：不通过，1：通过，默认0',
  `living_check` tinyint(2) DEFAULT NULL COMMENT '活体校验结果，0：不通过，1：通过，默认0',
  `fake_tag` tinyint(2) DEFAULT NULL COMMENT '虚假视频标识，0：正常，1：虚假视频，默认0',
  `tid` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '淘宝订单号',
  `create_time` datetime DEFAULT NULL COMMENT '下单时间',
  `pay_complete_time` datetime DEFAULT NULL COMMENT '支付完成时间',
  `refund_time` datetime DEFAULT NULL COMMENT '退款时间',
  `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `manual_check_time` datetime DEFAULT NULL COMMENT '转人工激活时间',
  `dn` int(6) NOT NULL COMMENT '路由id',
  `deliver_date_type` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '送货时间类型 01：不限时间 02：只工作日 03：只有双休日、节假日 04：不送货',
  `deliver_company_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '快递物流公司编码',
  `referrer_name` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '推荐人姓名',
  `referrer_phone` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '推荐人电话',
  `mashanggou` bigint(20) NOT NULL DEFAULT '0' COMMENT '码上购标记 0物流1上门2自提3码上购智能派单',
  `tendency_channel_two` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '二级渠道',
  `kingcard_channel_two` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '二级渠道',
  `cross_city` tinyint(2) NOT NULL DEFAULT '0' COMMENT '0 本地 1 异地',
  `mashanggou_back_state` tinyint(2) NOT NULL DEFAULT '0' COMMENT '0：正常订单 1: 码上购返回，转为物流方式  2:码上购返申请转为审单状态',
  `openacc_state` tinyint(2) NOT NULL DEFAULT '0' COMMENT '0未开户，1正在开户',
  `tendency_channel` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `tendency_channel_three` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '三级渠道',
  `kingcard_channel` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `kingcard_channel_three` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '三级渠道',
  `seller_remark` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '卖家留言',
  `phone_excode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '审单上传照片状态筛选码',
  `order_time` datetime DEFAULT NULL,
  `spec_remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '退单备注信息',
  `original_state` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '处理前订单状态',
  `applicant_phone` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '申请人电话',
  `applicant_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '申请人姓名',
  `invoce_type` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'NOW' COMMENT '发票类型 NOW：即时发票 MONTH：月结发票',
  `invoce_title` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '发票抬头',
  `invo_cont_code` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '发票内容编码',
  `tb_fz` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `alitrip_tag` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '0',
  `mult_code` tinyint(2) DEFAULT NULL COMMENT '0:非多号码订单 1:新带新2:亲情卡 3：老带新 5：老带新一带一',
  `verify_excode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT ' 审单标记异常筛选项',
  `post_tag` tinyint(2) DEFAULT NULL COMMENT '0：不邮寄 1：单一地址邮寄 2：多地址邮寄（拆分邮寄）',
  `mobile_channel` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付宝芝麻信息',
  `lgts_order` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '物流发货单号',
  PRIMARY KEY (`order_id`,`province_code`),
  KEY `city_code` (`city_code`) USING BTREE,
  KEY `create_time` (`create_time`) USING BTREE,
  KEY `order_time` (`order_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
